print(40>30)
print(40<30)
print(40==30)
print(40!=30)
print(40<=30)
print(40>=30)
print("___________________________")
print(True and True)
print(True and False)
print(False and True)
print(False and False)
print("____________________________")
print(False or True)
print(False or True)
print(False or True)
print(False or True)